#!/bin/bash

this=$(basename $0)

if [ -z $(which msfvenom) ]; then
	echo "MsfVenom not found in the PATH. You may need to manually add msfvenom to the executable path or (re-)install the metasploit framework."
fi

usage() {
    echo "MsfVList v1.0 (c) by NoodleOfDeath"
    echo
    echo "Simple tool to list msfvenom payloads, encoders, nops, platforms, architectures, encrypts, formats, and payload options backed by a cached memory."
    echo
    echo "Usage: $this [-h|--help] [-uv] <payloads | encoders | nops | platforms | archs | encrypts | formats | all | -p payload> [filter...]"
    echo "Example: $this payloads -v linux # prints all payloads with linux in the name verbosely"
    echo
    echo "Options:"
    echo "  -h|--help"
    echo "      displays this help message"
    echo "  -u|--update"
    echo "      forces cache update"
    echo "  -v|--verbose"
    echo "      verbose output when displaying payloads, encoders,  and nops"
    echo "  -p|--payload payload"
    echo "      payload to list options for"
    exit 0
}

args=()
update=false
verbose=0

while (( "$#" )); do
    case "$1" in
        -h|--help) usage;;
        -u|--update) update=true; shift;;
        -v|--verbose) verbose=1; shift;;
        -p|--payload) payload=$2; shift 2;;
        -*) echo "Error: Unsupported flag $1" >&2; exit 1;;
        *) args=( "${args[@]}" "$1" ); shift;;
    esac
done

target=${args[0]}
filter=${args[1]}

if [ -z "$filter" ]; then
    filter='.'
fi

lines=0
if [[ $verbose -gt 0 ]]; then
    lines=2
fi

cachedir=/var/cache/msfvenom
if [ ! -d $cachedir ]; then
    mkdir $cachedir
fi

GREEN='\033[0;32m'
NC='\033[0m'

output() {
    cache=$1
    if [ ! -f $cache ]; then
        echo "Unable to read cache from $cache"
        exit 1
    fi
	filter=" grep -i -e $filter"
	if [[ $lines -gt 0 ]]; then
		filter+=" -A $lines"
	fi
    cat $cache | eval $filter | while IFS="" read -r p; do
        item=$(echo $p | cut -d " " -f 1)
        if [[ $verbose -gt 0 ]]; then
            echo -e "${GREEN}$item${NC}"
            echo "  "$(echo $p | cut -d " " -f 2-)
            echo
        else
            echo $item
        fi
    done
}

if [ -z "$target" ]; then

    if [ -z "$payload" ]; then
        echo "No msfvenom list target or payload specified. Unable to list options."
        usage
        exit 1
    fi
    optcache=$cachedir/$(echo $payload | sed 's/\//_/g').cache
    if [ $update ] || [ ! -f $optcache ]; then
        echo "Generating options cache for $payload"
        msfvenom -p $payload --list-options > $optcache
    fi
    if [ -f $optcache ]; then
        cat $optcache
    else
        echo "Unable to find cache for payload $payload"
    fi

else

    if [ "$target" != "all" ] && [ "${target: -1}" != "s" ]; then
        target=$target"s"
    fi

    case "$target" in
        all|archs|encrypts|formats|platforms)
            if [ $update == true ] || [ ! -f $cachedir/$target.cache ]; then
                echo "Generating $target cache"
                msfvenom --list $target > $cachedir/$target.cache
            fi
            cat $cachedir/$target.cache
            ;;
        *)
            if [ $update == true ] || [ ! -f $cachedir/$target.cache ]; then
                echo "Generating $target cache"
                msfvenom --list $target | grep  '^\s*\w\+/\w\+' > $cachedir/$target.cache
            fi
            output $cachedir/$target.cache
            ;;
    esac

fi

